export default [
  { name: 'AMP - My AMP', baseUrl: 'https://api.cdr-api.amp.com.au/cds-au/v1' },
  { name: 'AMP Bank GO', baseUrl: 'https://pub.cdr-sme.amp.com.au/api/cds-au/v1' },
  { name: 'ANZ', baseUrl: 'https://api.anz/cds-au/v1' },
  { name: 'ANZ Plus', baseUrl: 'https://cdr.apix.anz/cds-au/v1' },
  { name: 'Adelaide Bank', baseUrl: 'https://api.cdr.adelaidebank.com.au/cds-au/v1' },
  { name: 'Alex.Bank', baseUrl: 'https://public.cdr.alex.com.au/cds-au/v1' },
  { name: 'Arab Bank Australia Limited', baseUrl: 'https://public.cdr.arabbank.com.au/cds-au/v1' },
  { name: 'Aussie Home Loans', baseUrl: 'https://aussie.openportal.com.au/cds-au/v1' },
  { name: 'Australian Military Bank', baseUrl: 'https://public.open.australianmilitarybank.com.au/cds-au/v1' },
  { name: 'Australian Mutual Bank LTD', baseUrl: 'https://internetbanking.australianmutual.bank/openbanking/cds-au/v1' },
  { name: 'Australian Unity Bank', baseUrl: 'https://open-banking.australianunity.com.au/cds-au/v1' },
  { name: 'Auswide Bank Ltd', baseUrl: 'https://api.auswidebank.com.au/openbanking/cds-au/v1' },
  { name: 'BCU Bank', baseUrl: 'https://public.cdr-api.bcu.com.au/cds-au/v1' },
  { name: 'BOQ Specialist', baseUrl: 'https://api.cds.boqspecialist.com.au/cds-au/v1' },
  { name: 'Bank Australia', baseUrl: 'https://public.cdr.bankaust.com.au/cds-au/v1' },
  { name: 'Bank First', baseUrl: 'https://public.cdr.bankfirst.com.au/cds-au/v1' },
  { name: 'Bank of China', baseUrl: 'https://api-gateway.bankofchina.com.au/cds-au/v1' },
  { name: 'Bank of Melbourne', baseUrl: 'https://digital-api.bankofmelbourne.com.au/cds-au/v1' },
  { name: 'Bank of Queensland Limited', baseUrl: 'https://api.cds.boq.com.au/cds-au/v1' },
  { name: 'Bank of Sydney', baseUrl: 'https://openbank.api.banksyd.com.au/cds-au/v1' },
  { name: 'Bank of us', baseUrl: 'https://api.bankofus.com.au/OpenBanking/cds-au/v1' },
  { name: 'BankSA', baseUrl: 'https://digital-api.banksa.com.au/cds-au/v1' },
  { name: 'BankVic', baseUrl: 'https://ib.bankvic.com.au/openbanking/cds-au/v1' },
  { name: 'Bankwest', baseUrl: 'https://open-api.bankwest.com.au/bwpublic/cds-au/v1' },
  { name: 'Bendigo Bank', baseUrl: 'https://api.cdr.bendigobank.com.au/cds-au/v1' },
  { name: 'Beyond Bank Australia', baseUrl: 'https://public.cdr.api.beyondbank.com.au/cds-au/v1' },
  { name: 'Border Bank', baseUrl: 'https://public.cdr.prd.borderbank.com.au/cds-au/v1' },
  { name: 'Broken Hill Bank', baseUrl: 'https://public.cdr-api.bhccu.com.au/cds-au/v1' },
  { name: 'CBA - CommBiz', baseUrl: 'https://cdr.commbiz.api.commbank.com.au/cbzpublic/cds-au/v1' },
  { name: 'Cairns bank', baseUrl: 'https://openbanking.cairnsbank.com.au/OpenBanking/cds-au/v1' },
  { name: 'Card Services', baseUrl: 'https://api.openbanking.cardservicesdirect.com.au/cds-au/v1' },
  { name: 'Central Murray Bank', baseUrl: 'https://secure.cmcu.com.au/openbanking/cds-au/v1' },
  { name: 'Central West CUL', baseUrl: 'https://ib.cwcu.com.au/openbanking/cds-au/v1' },
  { name: 'Citi', baseUrl: 'https://openbanking.api.citi.com.au/cds-au/v1' },
  { name: 'Coastline Bank', baseUrl: 'https://public.cdr-api.coastline.com.au/cds-au/v1' },
  { name: 'Coles Financial Services', baseUrl: 'https://api.openbanking.secure.coles.com.au/cds-au/v1' },
  { name: 'CommBank', baseUrl: 'https://api.commbank.com.au/public/cds-au/v1' },
  { name: 'CommFCU', baseUrl: 'https://netbank.communityfirst.com.au/cf-OpenBanking/cds-au/v1' },
  { name: 'Credit Union SA', baseUrl: 'https://openbanking.api.creditunionsa.com.au/cds-au/v1' },
  { name: 'DDH Graham', baseUrl: 'https://api.cds.ddhgraham.com.au/cds-au/v1' },
  { name: 'Defence Bank', baseUrl: 'https://product.defencebank.com.au/cds-au/v1' },
  { name: 'Dnister', baseUrl: 'https://public.cdr-api.dnister.com.au/cds-au/v1' },
  { name: 'Easy Street', baseUrl: 'https://ebranch.easystreet.com.au/es-OpenBanking/cds-au/v1' },
  { name: 'Family First', baseUrl: 'https://public.cdr.familyfirst.com.au/cds-au/v1' },
  { name: 'Fire Service Credit Union', baseUrl: 'https://public.cdr-api.fscu.com.au/cds-au/v1' },
  { name: 'Firefighters Mutual Bank', baseUrl: 'https://ob.tmbl.com.au/fmbank/cds-au/v1' },
  { name: 'First Option Bank', baseUrl: 'https://internetbanking.firstoption.com.au/OpenBanking/cds-au/v1' },
  { name: 'G&C Mutual Bank', baseUrl: 'https://ibank.gcmutualbank.com.au/OpenBanking/cds-au/v1' },
  { name: 'Gateway Bank', baseUrl: 'https://public.cdr-api.gatewaybank.com.au/cds-au/v1' },
  { name: 'Geelong Bank', baseUrl: 'https://online.geelongbank.com.au/OpenBanking/cds-au/v1' },
  { name: 'Goldfields Money', baseUrl: 'https://prd.bnk.com.au/cds-au/v1' },
  { name: 'Great Southern Bank', baseUrl: 'https://api.open-banking.greatsouthernbank.com.au/cds-au/v1' },
  { name: 'Great Southern Bank Business+', baseUrl: 'https://od1.open-banking.business.greatsouthernbank.com.au/api/cds-au/v1' },
  { name: 'Greater Bank Limited', baseUrl: 'https://public.cdr.greater.com.au/cds-au/v1' },
  { name: 'HSBC', baseUrl: 'https://public.ob.hsbc.com.au/cds-au/v1' },
  { name: 'HSBC Bank Australia Limited - Wholesale Banking', baseUrl: 'https://public.ob.business.hsbc.com.au/cds-au/v1' },
  { name: 'Health Professionals Bank', baseUrl: 'https://ob.tmbl.com.au/hpbank/cds-au/v1' },
  { name: 'Heartland', baseUrl: 'https://api.cdr.heartlandbank.com.au/cds-au/v1' },
  { name: 'Heritage Bank', baseUrl: 'https://product.api.heritage.com.au/cds-au/v1' },
  { name: 'Hiver Bank', baseUrl: 'https://ob.tmbl.com.au/hiver/cds-au/v1' },
  { name: 'Horizon Bank', baseUrl: 'https://onlinebanking.horizonbank.com.au/openbanking/cds-au/v1' },
  { name: 'Hume Bank', baseUrl: 'https://ibankob.humebank.com.au/OpenBanking/cds-au/v1' },
  { name: 'IMB Bank', baseUrl: 'https://openbank.openbanking.imb.com.au/cds-au/v1' },
  { name: 'ING BANK (Australia) Ltd', baseUrl: 'https://id.ob.ing.com.au/cds-au/v1' },
  { name: 'Illawarra Credit Union Limited', baseUrl: 'https://onlineteller.cu.com.au/OpenBanking/cds-au/v1' },
  { name: 'Judo Bank', baseUrl: 'https://public.open.judo.bank/cds-au/v1' },
  { name: 'Kogan Money Credit Cards', baseUrl: 'https://api.openbanking.cards.koganmoney.com.au/cds-au/v1' },
  { name: 'Laboratories Credit Union', baseUrl: 'https://internetbanking.lcu.com.au/OpenBanking/cds-au/v1' },
  { name: 'Liberty Financial', baseUrl: 'https://services.liberty.com.au/api/data-holder-public/cds-au/v1' },
  { name: 'ME Bank', baseUrl: 'https://public.openbank.mebank.com.au/cds-au/v1' },
  { name: 'ME Bank - ME Go', baseUrl: 'https://api.cds.mebank.com.au/cds-au/v1' },
  { name: 'MOVE Bank', baseUrl: 'https://openbanking.movebank.com.au/OpenBanking/cds-au/v1' },
  { name: 'Macquarie Bank Limited', baseUrl: 'https://api.macquariebank.io/cds-au/v1' },
  { name: 'Maitland Mutual Limited', baseUrl: 'https://openbanking.themutual.com.au/OpenBanking/cds-au/v1' },
  { name: 'MyState Bank', baseUrl: 'https://public.cdr.mystate.com.au/cds-au/v1' },
  { name: 'NATIONAL AUSTRALIA BANK', baseUrl: 'https://openbank.api.nab.com.au/cds-au/v1' },
  { name: 'Newcastle Permanent Building Society', baseUrl: 'https://openbank.newcastlepermanent.com.au/cds-au/v1' },
  { name: 'Northern Inland Credit Union Limited', baseUrl: 'https://secure.nicu.com.au/OpenBanking/cds-au/v1' },
  { name: 'ORANGE CREDIT UNION LTD', baseUrl: 'https://online.orangecu.com.au/openbanking/cds-au/v1' },
  { name: 'P&N Bank', baseUrl: 'https://public.cdr-api.pnbank.com.au/cds-au/v1' },
  { name: 'PayPal Australia', baseUrl: 'https://api.paypal.com/v1/identity/cds-au/v1' },
  { name: "People's Choice", baseUrl: 'https://ob-public.peopleschoice.com.au/cds-au/v1' },
  { name: 'Police Bank', baseUrl: 'https://public.cdr.prd.policebank.com.au/cds-au/v1' },
  { name: 'Police Credit Union Ltd', baseUrl: 'https://api.policecu.com.au/OpenBanking/cds-au/v1' },
  { name: 'QBANK', baseUrl: 'https://banking.qbank.com.au/openbanking/cds-au/v1' },
  { name: 'Qantas Premier Credit Cards', baseUrl: 'https://api.openbanking.qantasmoney.com/cds-au/v1' },
  { name: 'Qudos Bank', baseUrl: 'https://public.cdr.qudosbank.com.au/cds-au/v1' },
  { name: 'Queensland Country Bank', baseUrl: 'https://public.cdr-api.queenslandcountry.bank/cds-au/v1' },
  { name: 'RACQ Bank', baseUrl: 'https://cdrbank.racq.com.au/cds-au/v1' },
  { name: 'RAMS Financial Group Pty Ltd', baseUrl: 'https://digital-api.westpac.com.au/rams/cds-au/v1' },
  { name: 'RSL Money', baseUrl: 'https://public.open.rslmoney.com.au/cds-au/v1' },
  { name: 'Rabobank', baseUrl: 'https://openbanking.api.rabobank.com.au/public/cds-au/v1' },
  { name: 'Regional Australia Bank', baseUrl: 'https://public-data.cdr.regaustbank.io/cds-au/v1' },
  { name: 'Reliance Bank', baseUrl: 'https://ibanking.reliancebank.com.au/rel-openbanking/cds-au/v1' },
  { name: 'SWSbank', baseUrl: 'https://online.swsbank.com.au/openbanking/cds-au/v1' },
  { name: 'Southern Cross Credit Union', baseUrl: 'https://cdr.sccu.com.au/openbanking/cds-au/v1' },
  { name: 'St.George Bank', baseUrl: 'https://digital-api.stgeorge.com.au/cds-au/v1' },
  { name: 'Summerland Bank', baseUrl: 'https://public.cdr-api.summerland.com.au/cds-au/v1' },
  { name: 'Suncorp Bank', baseUrl: 'https://id-ob.suncorpbank.com.au/cds-au/v1' },
  { name: 'TMCU', baseUrl: 'https://banking.transportmutual.com.au/OpenBanking/cds-au/v1' },
  { name: 'Teachers Mutual Bank', baseUrl: 'https://ob.tmbl.com.au/tmbank/cds-au/v1' },
  { name: 'The Capricornian', baseUrl: 'https://public.cdr.onlinebanking.capricornian.com.au/cds-au/v1' },
  { name: 'The Mac', baseUrl: 'https://onlinebanking.themaccu.com.au/OpenBanking/cds-au/v1' },
  { name: 'Thriday', baseUrl: 'https://public.cdr.thriday.com.au/cds-au/v1' },
  { name: 'Traditional Credit Union', baseUrl: 'https://prd.tcu.com.au/cds-au/v1' },
  { name: 'Tyro Payments', baseUrl: 'https://public.cdr.tyro.com/cds-au/v1' },
  { name: 'UBank', baseUrl: 'https://public.cdr-api.86400.com.au/cds-au/v1' },
  { name: 'UniBank', baseUrl: 'https://ob.tmbl.com.au/unibank/cds-au/v1' },
  { name: 'Unity Bank', baseUrl: 'https://ibanking.unitybank.com.au/OpenBanking/cds-au/v1' },
  { name: 'Unloan', baseUrl: 'https://public.api.cdr.unloan.com.au/cds-au/v1' },
  { name: 'Up', baseUrl: 'https://api.up.com.au/cds-au/v1' },
  { name: 'Virgin Money', baseUrl: 'https://api.cds.virginmoney.com.au/cds-au/v1' },
  { name: 'Warwick Credit Union Ltd', baseUrl: 'https://openbanking.wcu.com.au/OpenBanking/cds-au/v1' },
  { name: 'Westpac', baseUrl: 'https://digital-api.westpac.com.au/cds-au/v1' },
  { name: 'Wise', baseUrl: 'https://au-cdrbanking-pub.wise.com/cds-au/v1' },
  { name: 'Woolworths Team Bank', baseUrl: 'https://online.woolworthsteambank.com.au/OpenBanking/cds-au/v1' },
  { name: 'bankWAW', baseUrl: 'https://onlinebanking.wawcu.com.au/OpenBanking/cds-au/v1' },
  { name: 'gmcu', baseUrl: 'https://secure.gmcu.com.au/OpenBanking/cds-au/v1' },
  { name: 'in1bank ltd.', baseUrl: 'https://cdr.in1bank.com.au/cds-au/v1' }
];
